# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "images/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # POSTS
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Paul Burdon", value: "paul_burdon" }
      - {label: "Image", name: "image", widget: "image"}    
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}
      - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "navtiles"
    label: "Navigation Tiles"
    folder: "_navtiles"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "navtile"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Href", name: "href", widget: "string"}
      - {label: "Custom Tags", name: "customtags", widget: "relation", collection: "customtags", displayFields: ["customtag"], searchFields: ["customtag"],  valueField: "customtag",  multiple: true, required: false}
  - name: "features"
    label: "Feature Tiles"
    folder: "_features"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "navtile"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Icon", name: "icon", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Custom Tags", name: "customtags", widget: "relation", collection: "customtags", displayFields: ["customtag"], searchFields: ["customtag"],  valueField: "customtag",  multiple: true, required: false}
  - name: "customtags"  
    label: "Custom Tags"
    folder: "_customtags"
    create: true
    fields:       
      - {label: "Layout", name: "layout", widget: "hidden", default: "customtag"}
      - {label: "tag", name: "tag", widget: "string"}
  - name: "bannerslides"
    label: "Banner Slides"
    folder: "_bannerslides"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Url", name: "url", widget: "string"}
      - {label: "Custom Tags", name: "customtags", widget: "relation", collection: "customtags", displayFields: ["customtag"], searchFields: ["customtag"],  valueField: "customtag",  multiple: true, required: false}
  - name: "testimonials"
    label: "Testimonials"
    folder: "_testimonials"
    create: true
    fields:
     
      - label: "Image" 
        name: "image"
        widget: "image"
        default: ""
        media_library:
             config:
               multiple: false
      - label: "Thumb" 
        name: "thumb"
        widget: "image"
        default: ""
        media_library:
             config:
               multiple: false
      - {label: "Excerpt", name: "title", widget: "string"}         
      - {label: "Age", name: "age", widget: "number", default: 30, valueType: "int"}
      - {label: "Patient-type", name: "patient-type", widget: "string"}
      - {label: "Gender", name: "gender", widget: "string"}
      - {label: "Show Excerpt", name: "showexcerpt", widget: "boolean", default: false}
      - {label: "Show Dark Background", name: "darkback", widget: "boolean", default: true}      
